### ISSUE TITLE
Installation should check if the user is part of the docker group

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#184] opened 2024-08-21 06:25 UTC
## Problem
The current installation requires that the user who is running it is part of the docker group. In the installation manual, we have given instruction on how to add to the group and specifically that the user has to restart the shell before proceeding for the new addition to take effect. 
However many users do not read the installation manual and try to install without the restart or without adding the user to group.

## Requirement
We should check at the beginning of the script if the user is part of the docker group. If not, then we should ask him to add himself to the group, restart the shell and try again. We should not go ahead with the installation in this case.

**Comment by viraj89** [comment] 2024-08-22 12:04
adding a disclaimer: 
to check about the pre-requisite at the beginning of the installation itself.

**Comment by prasad-takale-eminds** [comment] 2024-12-02 05:35
Duplicate of issue #208

**Closed by prasad-takale-eminds** 2024-12-02 05:35 UTC
Labels: enhancement
